# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "VagrantPrueba1" do |vagrant|
        vagrant.vm.box = "generic/centos8"
        vagrant.vm.hostname = "VagrantPrueba1"
        vagrant.vm.network :private_network, ip: "192.168.10.70"
        vagrant.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--ioapic", "on"]
            v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            v.customize ["modifyvm", :id, "--name", "CursoCliente"]
            v.customize ["modifyvm", :id, "--memory", 2048]
            v.customize ["modifyvm", :id, "--cpus", 2]
        end
        $COMMANDS = <<-'BLOCK'
        sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config;
        sudo yum update && sudo yum upgrade
        sudo systemctl restart sshd
        sudo yum -y install python3
        sudo yum -y install epel-release
        sudo pip3 install --upgrade pip
        sudo pip3 install ansible
        echo "root:vagrant" | sudo chpasswd
        BLOCK
        vagrant.vm.provision "shell", inline: $COMMANDS
    end
end